# Generated by Django 4.1.5 on 2023-02-01 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='contentTwo',
        ),
    ]
