# Generated by Django 4.1.5 on 2023-02-03 17:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0003_rename_reviews_blog_contenttwo_blog_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='contentTwo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
