# Generated by Django 4.1.5 on 2023-02-05 03:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0005_blog_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='post_date',
        ),
        migrations.AddField(
            model_name='blog',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
