# Generated by Django 4.1.5 on 2023-02-12 05:36

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0007_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='contentTwo',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
