# Generated by Django 4.1.5 on 2023-02-12 13:51

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0008_alter_blog_contenttwo_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='ingredients',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
